// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// ClipboardMock is a mock implementation of ui.Clipboard.
//
//	func TestSomethingThatUsesClipboard(t *testing.T) {
//
//		// make and configure a mocked ui.Clipboard
//		mockedClipboard := &ClipboardMock{
//			CopyFunc: func(content string) error {
//				panic("mock out the Copy method")
//			},
//		}
//
//		// use mockedClipboard in code that requires ui.Clipboard
//		// and then make assertions.
//
//	}
type ClipboardMock struct {
	// CopyFunc mocks the Copy method.
	CopyFunc func(content string) error

	// calls tracks calls to the methods.
	calls struct {
		// Copy holds details about calls to the Copy method.
		Copy []struct {
			// Content is the content argument value.
			Content string
		}
	}
	lockCopy sync.RWMutex
}

// Copy calls CopyFunc.
func (mock *ClipboardMock) Copy(content string) error {
	if mock.CopyFunc == nil {
		panic("ClipboardMock.CopyFunc: method is nil but Clipboard.Copy was just called")
	}
	callInfo := struct {
		Content string
	}{
		Content: content,
	}
	mock.lockCopy.Lock()
	mock.calls.Copy = append(mock.calls.Copy, callInfo)
	mock.lockCopy.Unlock()
	return mock.CopyFunc(content)
}

// CopyCalls gets all the calls that were made to Copy.
// Check the length with:
//
//	len(mockedClipboard.CopyCalls())
func (mock *ClipboardMock) CopyCalls() []struct {
	Content string
} {
	var calls []struct {
		Content string
	}
	mock.lockCopy.RLock()
	calls = mock.calls.Copy
	mock.lockCopy.RUnlock()
	return calls
}
